In [1]:
import numpy as np

In [2]:
x = np.random.rand(4, 5)

# y = np.sum(x, axis=1)


In [8]:
x.shape

(4, 5)

In [11]:
np.sum(x, axis=1, keepdims=True).shape

(4, 1)

In [1]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(A)
print(B)


# Matrix multiplication using matmul
C_matmul = np.matmul(A, B)
print("Matrix product with matmul:\n", C_matmul)

# Matrix multiplication using @ operator
C_at_operator = A @ B
print("Matrix product with @ operator:\n", C_at_operator)

# Matrix multiplication using dot (for 2D arrays)
C_dot = np.dot(A, B)
print("Matrix product with dot:\n", C_dot)

# Element-wise multiplication
C_element_wise = np.multiply(A, B)
print("Element-wise multiplication:\n", C_element_wise)


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
Matrix product with matmul:
 [[19 22]
 [43 50]]
Matrix product with @ operator:
 [[19 22]
 [43 50]]
Matrix product with dot:
 [[19 22]
 [43 50]]
Element-wise multiplication:
 [[ 5 12]
 [21 32]]


In [7]:
np.transpose(A)

array([[1, 3],
       [2, 4]])